// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Oc14FC3Lt85ihoGsWZ_YE-DE0Qib1ps',
    appId: '1:251373079558:web:025820071148e03ef8c787',
    messagingSenderId: '251373079558',
    projectId: 'wechatapp-b8634',
    authDomain: 'wechatapp-b8634.firebaseapp.com',
    storageBucket: 'wechatapp-b8634.appspot.com',
    measurementId: 'G-MS4Z6KQV7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChj3HPM5Y0L6iu8VNb69I16JOTUEWllyw',
    appId: '1:251373079558:android:909a0a1232068c2cf8c787',
    messagingSenderId: '251373079558',
    projectId: 'wechatapp-b8634',
    storageBucket: 'wechatapp-b8634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8LjLWzS8qv8IcAhbYlv9e5I8a90xn5es',
    appId: '1:251373079558:ios:3e98cd2f07f0665af8c787',
    messagingSenderId: '251373079558',
    projectId: 'wechatapp-b8634',
    storageBucket: 'wechatapp-b8634.appspot.com',
    iosBundleId: 'com.example.weChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8LjLWzS8qv8IcAhbYlv9e5I8a90xn5es',
    appId: '1:251373079558:ios:3e98cd2f07f0665af8c787',
    messagingSenderId: '251373079558',
    projectId: 'wechatapp-b8634',
    storageBucket: 'wechatapp-b8634.appspot.com',
    iosBundleId: 'com.example.weChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Oc14FC3Lt85ihoGsWZ_YE-DE0Qib1ps',
    appId: '1:251373079558:web:e6d99090998899ebf8c787',
    messagingSenderId: '251373079558',
    projectId: 'wechatapp-b8634',
    authDomain: 'wechatapp-b8634.firebaseapp.com',
    storageBucket: 'wechatapp-b8634.appspot.com',
    measurementId: 'G-S15193V6CT',
  );

}